package uz.sudev.atmsystem.entity.enums;

public enum CashType {
    THOUSAND_SUMS,
    FIVE_THOUSAND_SUMS,
    TEN_THOUSAND_SUMS,
    FIFTY_THOUSAND_SUMS,
    HUNDRED_THOUSAND_SUMS,
    ONE_DOLLAR,
    FIVE_DOLLARS,
    TEN_DOLLARS,
    TWENTY_DOLLARS,
    FIFTY_DOLLARS,
    HUNDRED_DOLLARS
}
